### ISSUE TITLE
neovim plugins to look into

### ISSUE THREAD

**Issue by rucas** [rucas/derpfiles#16]
# TODO
- [ ] http://liuchengxu.org/vista.vim/
- [ ] https://github.com/paroxayte/vwm.vim
- [ ] https://github.com/ludovicchabant/vim-gutentags
